### ISSUE TITLE
Make objects constants

### ISSUE THREAD

**Issue by Rezenders** [remaro-network/dlToPlanning#21]
@tobiaswjohn Due to some technical limitations in PlanSys, it would be better to add the Abox of Classes as constants in the problem file instead of adding them as objects in the domain file. Do you think you can change that easily? I think it would be easier to change the translation tool than to change PlanSys.

**Comment by tobiaswjohn** [comment]
Just to clarify your request: You want to have the individuals from the ontology as constants in the domain file rather than having them as objects in the problem file? E.g. `fd_follow_pipeline` should become a constant instead of an object? 
I think, this is considered bad style in PDDL, but I can do that for everything that is not a number. (If I also do it for numbers, the faster update of the problem file is no longer possible)

**Comment by Rezenders** [comment]
Thanks!

> I think, this is considered bad style in PDDL

Ok, when we get the system running, I can try to make these changes on the PlanSys side. But I guess it is better to leave it for later
